markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "zearom32"
markdown: rdiscount

author: "zearom32"
atom-baseurl: "http://zearom32.github.io"
disqus: "zearom32"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: 
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

excerpt_separator: <!--more-->